from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, DateTime

Base = declarative_base()

class TnDataBscInfo(Base):

    def as_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}

    __tablename__ = "tn_data_bsc_info"

    sn = Column(Integer)
    dtst_cd = Column(String, primary_key=True)
    dtst_dtl_cd = Column(String, primary_key=True)
    dtst_nm = Column(String)
    dtst_expln = Column(String)
    pvdr_site_cd = Column(String)
    pvdr_inst_cd = Column(String)
    pvdr_dept_nm = Column(String)
    pvdr_pvsn_mthd_cd = Column(String)
    pvdr_data_se_vl_one = Column(String)
    pvdr_data_se_vl_two = Column(String)
    pvdr_data_se_vl_three = Column(String)
    pvdr_updt_cycle_cd = Column(String)
    pvdr_sou_data_pvsn_stle = Column(String)
    link_ntwk_otsd_insd_se = Column(String)
    link_pvdr_url = Column(String)
    link_data_clct_url = Column(String)
    link_db_id = Column(String)
    link_tbl_phys_nm = Column(String)
    link_dtst_se_cd = Column(String)
    link_file_crt_yn = Column(String)
    link_file_merg_yn = Column(String)
    link_file_extn = Column(String)
    link_file_sprtr = Column(String)
    link_yn = Column(String)
    link_se_cd = Column(String)
    insd_trsm_yn = Column(String)
    clct_yn = Column(String)
    link_clct_mthd = Column(String)
    link_clct_mthd_dtl_cd = Column(String)
    link_clct_cycle_cd = Column(String)
    link_clct_job_id = Column(String)
    pbadms_fld_lclsf_cd = Column(String)
    pbadms_fld_mclsf_cd = Column(String)
    pbadms_fld_sclsf_cd = Column(String)
    rel_kywd_nm = Column(String)
    non_idntf_prcs_yn = Column(String)
    encpt_yn = Column(String)
    geom_utlz_yn = Column(String)
    dw_load_yn = Column(String)
    dw_load_mthd_cd = Column(String)
    dw_tbl_phys_nm = Column(String)
    addr_refine_yn = Column(String)
    dtwrh_utlz_yn = Column(String)
    data_rls_se_cd = Column(String)
    portal_dwnld_pvsn_yn = Column(String)
    data_list_exprs_yn = Column(String)
    use_yn = Column(String)
    crt_id = Column(String)
    crt_dt = Column(DateTime)
    rmrk = Column(String)
    rmrk_two = Column(String)
    rmrk_three = Column(String)
    data_se_col_one = Column(String)
    data_se_col_two = Column(String)
    rfrnc_phys_tbl_nm = Column(String)
    rfrnc_col_nm = Column(String)
    crtr_del_col_nm = Column(String)
    mdfcn_id = Column(String)
    mdfcn_dt = Column(DateTime)
    pvdr_site_nm = Column(String)